#!/bin/bash

echo "=================================================="
echo "    VideoPlayer getTech 错误修复 - 验证测试"
echo "=================================================="
echo ""
echo "✅ 已完成的修复:"
echo "   1. VideoPlayer.vue - 移除不安全的tech()调用"
echo "   2. 路由配置 - 恢复正常路由"
echo "   3. 调试信息 - 保留以便验证"
echo ""
echo "=================================================="
echo "   请按以下步骤测试"
echo "=================================================="
echo ""
echo "步骤1: 打开浏览器"
echo "-------"
echo "访问: http://localhost:3000/files/71"
echo ""

PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null)
if [ -n "$PUBLIC_IP" ]; then
    echo "或使用公网IP: http://$PUBLIC_IP:3000/files/71"
    echo ""
fi

echo "步骤2: 强制刷新页面"
echo "-------"
echo "按 Ctrl+F5 (Windows/Linux) 或 Cmd+Shift+R (Mac)"
echo "这会清除缓存并重新加载"
echo ""

echo "步骤3: 检查页面"
echo "-------"
echo "应该看到完整的文件详情页面，包括："
echo "  ✓ 页面头部 (返回按钮)"
echo "  ✓ 文件信息卡片"
echo "  ✓ 黄色调试信息框 (显示各个条件)"
echo "  ✓ 绿色提示: '✓ VideoPlayer组件应该显示在下方'"
echo "  ✓ 黑色视频播放器区域"
echo ""

echo "步骤4: 检查错误"
echo "-------"
echo "按 F12 打开开发者工具 → Console 标签页"
echo ""
echo "❌ 不应该看到的错误:"
echo "  - 'getTech is not a function'"
echo "  - 任何红色错误信息"
echo ""
echo "✅ 应该看到的日志:"
echo "  - 'Computing previewUrl: ...'"
echo "  - 'Preview URL generated: /api/v1/files/71/preview'"
echo "  - 'Video.js player is ready'"
echo "  - 'Tech in use: html5' (或 'Tech in use: flvjs')"
echo ""

echo "步骤5: 测试播放"
echo "-------"
echo "  1. 点击视频播放器的播放按钮"
echo "  2. 视频应该开始播放"
echo "  3. 控制条应该正常响应 (暂停、音量、进度)"
echo ""

echo "=================================================="
echo "   如果测试失败"
echo "=================================================="
echo ""
echo "如果仍然出现 'getTech' 错误:"
echo "  1. 完全关闭浏览器并重新打开"
echo "  2. 清除浏览器缓存 (Ctrl+Shift+Delete)"
echo "  3. 使用隐私/无痕模式测试"
echo "  4. 尝试其他浏览器 (Chrome, Firefox, Edge)"
echo ""

echo "如果VideoPlayer不显示:"
echo "  1. 检查调试信息框中的'最终条件'是否为 true"
echo "  2. 如果是 false，截图调试信息框"
echo "  3. 查看Console中是否有其他错误"
echo "  4. 尝试访问备用页面:"
echo "     - 简化版: http://localhost:3000/files/71/simple"
echo "     - 测试页: http://localhost:3000/test-video"
echo ""

echo "=================================================="
echo "   快速诊断命令"
echo "=================================================="
echo ""
echo "检查Vite服务器日志:"
echo "  tail -30 /tmp/vite-reload.log"
echo ""
echo "检查后端服务:"
echo "  curl http://localhost:8080/health | jq"
echo ""
echo "完整系统诊断:"
echo "  /home/ec2-user/openwan/diagnose-videoplayer.sh"
echo ""

echo "=================================================="
echo "   需要反馈的信息"
echo "=================================================="
echo ""
echo "如果问题仍然存在，请提供:"
echo "  1. 是否还有 'getTech' 错误？ (是/否)"
echo "  2. VideoPlayer是否显示？ (是/否)"
echo "  3. 调试信息框显示的'最终条件'值 (true/false)"
echo "  4. Console的完整日志 (截图或复制文本)"
echo "  5. 使用的浏览器和版本"
echo ""

echo "=================================================="
echo ""
echo "🎯 现在请打开浏览器测试:"
echo "   http://localhost:3000/files/71"
echo ""
echo "   然后告诉我测试结果！"
echo ""
echo "=================================================="
